import { Heart, Image, Code, Palette } from "lucide-react";

function Credits() {
  return (
    <div className="min-h-screen bg-slate-50 py-12">
      <div className="container mx-auto px-6 max-w-4xl">
        {/* Header */}
        <div className="text-center mb-12">
          <h1 className="text-4xl font-bold text-slate-800 mb-4">Credits</h1>
          <p className="text-lg text-slate-600">
            Acknowledging the amazing resources and people that made
            TerraFamilia possible
          </p>
        </div>

        {/* Developer Section */}
        <div className="bg-white rounded-lg shadow-md p-8 mb-6 border border-slate-200">
          <div className="flex items-center gap-3 mb-4">
            <Code className="text-cyan-600" size={28} />
            <h2 className="text-2xl font-bold text-slate-800">Development</h2>
          </div>
          <div className="ml-10">
            <p className="text-slate-700 mb-2">
              <span className="font-semibold">Developer:</span> QW
            </p>
            <p className="text-slate-600 text-sm mb-4">
              Built with React, TypeScript, TailwindCSS, and Supabase
            </p>

            <p className="mb-5">
              This website was designed and developed free of charge, if you are
              willing and able, buy them a coffee 😊
            </p>

            {/* Ko-fi Button */}
            <a
              href="https://ko-fi.com/qw1999"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-6 py-3 bg-cyan-600 hover:bg-cyan-700 text-white font-semibold rounded-lg transition-colors shadow-md hover:shadow-lg"
            >
              <svg className="w-5 h-5" viewBox="0 0 24 24" fill="currentColor">
                <path d="M23.881 8.948c-.773-4.085-4.859-4.593-4.859-4.593H.723c-.604 0-.679.798-.679.798s-.082 7.324-.022 11.822c.164 2.424 2.586 2.672 2.586 2.672s8.267-.023 11.966-.049c2.438-.426 2.683-2.566 2.658-3.734 4.352.24 7.422-2.831 6.649-6.916zm-11.062 3.511c-1.246 1.453-4.011 3.976-4.011 3.976s-.121.119-.31.023c-.076-.057-.108-.09-.108-.09-.443-.441-3.368-3.049-4.034-3.954-.709-.965-1.041-2.7-.091-3.71.951-1.01 3.005-1.086 4.363.407 0 0 1.565-1.782 3.468-.963 1.904.82 1.832 3.011.723 4.311zm6.173.478c-.928.116-1.682.028-1.682.028V7.284h1.77s1.971.551 1.971 2.638c0 1.913-.985 2.667-2.059 3.015z" />
              </svg>
              Support on Ko-fi
            </a>
          </div>
        </div>

        {/* Images Section */}
        <div className="bg-white rounded-lg shadow-md p-8 mb-6 border border-slate-200">
          <div className="flex items-center gap-3 mb-4">
            <Image className="text-cyan-600" size={28} />
            <h2 className="text-2xl font-bold text-slate-800">Images</h2>
          </div>
          <div className="ml-10 space-y-3">
            <div>
              <p className="text-slate-700 font-semibold mb-1">Cover Image</p>
              <p className="text-slate-600 text-sm">
                Provided by{" "}
                <a
                  href="https://stock.adobe.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-cyan-600 hover:text-cyan-700 underline"
                >
                  Adobe Stock
                </a>{" "}
                (Free Stock)
              </p>
            </div>
            <div>
              <p className="text-slate-700 font-semibold mb-1">User Avatars</p>
              <p className="text-slate-600 text-sm">
                Generated by{" "}
                <a
                  href="https://ui-avatars.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-cyan-600 hover:text-cyan-700 underline"
                >
                  UI Avatars
                </a>
              </p>
            </div>
          </div>
        </div>

        {/* Icons Section */}
        <div className="bg-white rounded-lg shadow-md p-8 mb-6 border border-slate-200">
          <div className="flex items-center gap-3 mb-4">
            <Palette className="text-cyan-600" size={28} />
            <h2 className="text-2xl font-bold text-slate-800">Icons</h2>
          </div>
          <div className="ml-10">
            <p className="text-slate-700 mb-2">
              <span className="font-semibold">Icon Library:</span>{" "}
              <a
                href="https://lucide.dev"
                target="_blank"
                rel="noopener noreferrer"
                className="text-cyan-600 hover:text-cyan-700 underline"
              >
                Lucide Icons
              </a>
            </p>
            <p className="text-slate-600 text-sm">
              Beautiful, consistent open-source icons used throughout the
              application
            </p>
          </div>
        </div>

        {/* Technologies Section */}
        <div className="bg-white rounded-lg shadow-md p-8 mb-6 border border-slate-200">
          <div className="flex items-center gap-3 mb-4">
            <Code className="text-cyan-600" size={28} />
            <h2 className="text-2xl font-bold text-slate-800">Technologies</h2>
          </div>
          <div className="ml-10 space-y-2">
            <p className="text-slate-700">
              <span className="font-semibold">Frontend:</span>{" "}
              <a
                href="https://react.dev"
                target="_blank"
                rel="noopener noreferrer"
                className="text-cyan-600 hover:text-cyan-700 underline"
              >
                React
              </a>
              ,{" "}
              <a
                href="https://www.typescriptlang.org"
                target="_blank"
                rel="noopener noreferrer"
                className="text-cyan-600 hover:text-cyan-700 underline"
              >
                TypeScript
              </a>
              ,{" "}
              <a
                href="https://tailwindcss.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-cyan-600 hover:text-cyan-700 underline"
              >
                TailwindCSS
              </a>
            </p>
            <p className="text-slate-700">
              <span className="font-semibold">Backend:</span>{" "}
              <a
                href="https://supabase.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-cyan-600 hover:text-cyan-700 underline"
              >
                Supabase
              </a>{" "}
              (PostgreSQL, Authentication, Storage)
            </p>
            <p className="text-slate-700">
              <span className="font-semibold">Build Tool:</span>{" "}
              <a
                href="https://vitejs.dev"
                target="_blank"
                rel="noopener noreferrer"
                className="text-cyan-600 hover:text-cyan-700 underline"
              >
                Vite
              </a>
            </p>
            <p className="text-slate-700">
              <span className="font-semibold">Routing:</span>{" "}
              <a
                href="https://reactrouter.com"
                target="_blank"
                rel="noopener noreferrer"
                className="text-cyan-600 hover:text-cyan-700 underline"
              >
                React Router
              </a>
            </p>
          </div>
        </div>

        {/* Thank You Section */}
        <div className="bg-linear-to-br from-cyan-50 to-slate-100 rounded-lg shadow-md p-8 border-2 border-cyan-200 text-center">
          <Heart className="text-cyan-600 mx-auto mb-4" size={40} />
          <h2 className="text-2xl font-bold text-slate-800 mb-2">Thank You</h2>
          <p className="text-slate-600">
            To all the open-source contributors and creators who make projects
            like this possible. Your work helps build stronger communities.
          </p>
        </div>
      </div>
    </div>
  );
}

export default Credits;
